#pragma once

// Auto-generated binary resources from mikobench/dist/editor/index.html
// Do not edit this file manually

// Function to get the HTML content as a C-string
const char* GetEditorHTML();

// Function to get the size of the HTML content
unsigned int GetEditorHTMLSize();
