#pragma once

// Auto-generated binary resources from docs/resources/splash.png
// Do not edit this file manually

// Function to get the splash screen PNG data
const unsigned char *GetSplashScreenData();

// Function to get the size of the splash screen PNG data
unsigned int GetSplashScreenSize();
