#pragma once

// Auto-generated binary resources from mikobench/dist/index.html
// Do not edit this file manually

extern const unsigned char webapp_html[];
extern const unsigned int webapp_html_size;

// Function to get the embedded HTML content
const char* GetWebAppHTML();
unsigned int GetWebAppHTMLSize();
