name: Build MikoIDE

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25'
    
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'
        cache: false
    
    - name: Install dependencies
      run: bun install
    
    - name: Build frontend
      run: bun run build
    
    - name: Convert HTML to binary
      run: bun run buildtobin
    
    - name: Build main application
      run: bun run build:cmake main --verbose
    
    - name: Create portable package
      run: bun run tools/prod.ts --portable
      shell: pwsh
    
    - name: Create installer package
      run: bun run tools/prod.ts --installer
      shell: pwsh
    
    - name: Upload portable artifact
      uses: actions/upload-artifact@v4
      with:
        name: mikoide-windows-portable
        path: out/mikoide_win-portable.zip
    
    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: mikoide-windows-installer
        path: out/mikoide_setup.exe