name: Build MikoIDE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Install NSIS (via Scoop)
        shell: powershell
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install JS dependencies
        run: bun install

      - name: Build MikoIDE (Release)
        run: bun run build:release:win

